fisrtProject/blogs/urls.py
from . import views
from django.urls import path

app_name = 'blogs' # untuk namespace

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.single, name='single'),
    path('blogs/<int:id>', views.comment, name='comment'),
    path('comment-edit/<int:id>', views.comment_edit, name='comment-edit'),
]

hander404 = 'views.handler404'

fisrtProject/fisrtProject/urls.py
from . import views
from . import coba
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('coba/', coba.Testing),
    path('admin/', admin.site.urls),
    path('kontak/', views.contact, name='contact')
]

urlpatterns += staticfiles_urlpatterns()

fisrtProject/blogs/models.py
from django.db import models

# membuat model Blogs
class Blogs(models.Model):
	title = models.CharField(max_length=100)
	desc = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True) # auto_now_add adalah fungsi dari django

	# menampilkan title saat memanggil Blogs.objects.all() di dalam shell
	def __str__(self):
		return self.title

# buat class comment
class Comment(models.Model):
	blog = models.ForeignKey(Blogs, on_delete=models.CASCADE)
	desc = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)

fisrtProject/blogs/forms.py
from .models import Comment
from django import forms
from django.core import validators

class CommentForm(forms.ModelForm):
    desc = forms.CharField(required=True, widget=forms.Textarea, validators=[validators.MinLengthValidator(5)])

    class Meta:
        model = Comment
        fields = ['desc']

fisrtProject/fisrtProject/forms.py
from django import forms
from django.core import validators

class ContactForm(forms.Form):
	name = forms.CharField()
	email = forms.EmailField()
	subject = forms.CharField(widget=forms.Textarea)
	# # untuk clean_method
	# honeypot = forms.CharField(widget=forms.Textarea, required=False) 
	honeypot = forms.CharField(widget=forms.HiddenInput, required=False, validators=[validators.MaxLengthValidator(0)])

	# def clean_honeypot(self):
	# 	honeypot = self.cleaned_data['honeypot']
	# 	if len(honeypot):    # cek apa ada panjang di honeypot
	# 		raise forms.ValidationError('Ngga boleh diisi dong')
	# 	# jika tidak ada kita return honeypot
	# 	return honeypot

fisrtProject/blogs/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Blogs, Comment
from django.contrib import messages
from django.urls import reverse
from . import forms

def handler404(request):
	return render(request, '404.html', status=404)

def index(request):
	blogs = Blogs.objects.all()				   
	return render(request, 'blogs/index.html', {'blogs':blogs})

def single(request, id):
	# blog = Blogs.objects.get(pk = id) # pk adalah primary key
	blog = get_object_or_404(Blogs, pk=id)
	form = forms.CommentForm()
	return render(request, 'blogs/single.html', {'blog':blog, 'form':form})


def comment(request, id):
	blog = get_object_or_404(Blogs, pk=id)
	form = forms.CommentForm()

	if request.method == 'POST':
		form = forms.CommentForm(request.POST)
		if form.is_valid():
			newDesc = request.POST['desc']
			blog.comment_set.create(desc=newDesc)
			messages.success(request, 'Berhasil Submit Komentar')
			return HttpResponseRedirect(reverse('blogs:index'))

	return render(request, 'blogs/single.html', {'blog':blog, 'form':form})

def comment_edit(request, id):
	comment = get_object_or_404(Comment, pk=id)
	form = forms.CommentForm(instance=comment)

	if request.method == 'POST':
		form = forms.CommentForm(instance=comment, data=request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Komentar Berhasil di Update!!')
			return HttpResponseRedirect(reverse('blogs:index'))

	return render(request, 'blogs/comment-edit.html', {'comment':comment, 'form':form})

fisrtProject/fisrtProject/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib import messages
from django.core.mail import send_mail
from . import forms

def welcome(request):
	return render(request, 'welcome.html')

def contact(request):
	form = forms.ContactForm()

	# buat handle form
	if request.method == 'POST':
		form = forms.ContactForm(request.POST)
		if form.is_valid():

			send_mail(
					'dari kontak website',      # subject
					request.POST['subject'],    # message/pesan
					request.POST['email'],      # email pengirim
					['tomsun@entry.co'],        # email yang dituju
					fail_silently=False,        
				)

			# messages.add_message(request, messages.WARNING, 'text pesan') # kita bisa menggunakan flash message seperti ini
			messages.success(request, 'Berhasil Kirim Email')
			return HttpResponseRedirect(reverse('contact'))

	return render(request, 'contact.html', {'form':form})

fisrtProject/blogs/templates/blogs/comment-edit.html
{% extends 'base.html' %}

{% block title %}
	Edit Komentar
{% endblock %}

{% block content %}
		<form action="{% url 'blogs:comment-edit' comment.id %}" method="post">
			
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Edit Komentar">
			
		</form>
{% endblock %}

fisrtProject/blogs/templates/blogs/index.html
{% extends 'base.html' %}

{% block title %}
	Blogs List Models
{% endblock %}

{% block content %}
	{% for blog in blogs %}
		<a href="{% url 'blogs:single' id=blog.id %}">
			<h1>{{ blog.title }}</h1>
		</a>
		<p>{{ blog.desc }}</p>
	{% endfor %}
{% endblock %}

fisrtProject/blogs/templates/blogs/single.html
{% extends 'base.html' %}

{% block title %}
	{{ blog.title }}
{% endblock %}

{% block content %}
		<p>{{ blog.desc }}</p>
		<p>{{ blog.created_at }}</p>

		<hr>
		<h2>Komentar</h2>

		<form action="{% url 'blogs:comment' blog.id %}" method="post">
			
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Kirim Komentar">
			
		</form>

		{% for comment in blog.comment_set.all %} <!- kita menggunakan fungsi _set jadi masukan namaEntry_set.all ->
		<p> {{ comment.desc }} - 
			<a href="{% url 'blogs:comment-edit' comment.id %}">Edit</a>
		</p>
		{% endfor %}
{% endblock %}

fisrtProject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'css/layout.css' %}">
	<title>Halaman Blogs</title>
</head>
<body>
	<h1>{% block title %}{% endblock %}</h1>

	<nav>
		<a href="/">Home</a>
		<a href="{% url 'blogs:index' %}">Blog</a>
		<a href="/kontak">Contact Us</a>
	</nav>

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<hr>

	{% block content %}

	{% endblock %}
</body>
</html>

fisrtProject/templates/contact.html
{% extends 'base.html' %}

{% block title %}
	Halaman Contact
{% endblock %}

{% block content %}
	<!-- as_p artinya form akan dibungkus sebagai paragraf -->
	<form action="{% url 'contact' %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Kirim Email">
	</form> 
{% endblock %}

fisrtProject/templates/welcome.html
{% extends 'base.html' %}

{% block title %}
	Blogs Welcome
{% endblock %}

{% block content %}
	<p>Welcome to My Website</p>
{% endblock %}